// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace Demo.CompiledModels
{
    public partial class DemoContextModel
    {
        partial void Initialize()
        {
            var security = SecurityEntityType.Create(this);

            SecurityEntityType.CreateAnnotations(security);

            AddAnnotation("ProductVersion", "7.0.10");
        }
    }
}
