// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace Demo.CompiledModels
{
    [DbContext(typeof(DemoContext))]
    public partial class DemoContextModel : RuntimeModel
    {
        static DemoContextModel()
        {
            var model = new DemoContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static DemoContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
